import "../globals.css";
import { Bebas_Neue } from "next/font/google";

const inter = Bebas_Neue({
  subsets: ["latin"],
  weight: "400",
});

export const metadata = {
  title: "Luxocars |  Authenticate",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${inter.className} bg-[#000002] fadeIn`}>
        {children}
      </body>
    </html>
  );
}
